# MANIPULER DES DONNES NUMPY

In [1]:
# créer des données avec numpy
import numpy as np

In [ ]:
help(np.array) # demander de l'aide

In [3]:
# la valeur manquante est géré par  np.nan
Matrice = np.array([[1,2,3],[4,5,6],[7,np.nan,9]])

In [4]:
# la valeur manquante
a = float('nan'); b = np.nan ; 
a2 = str('nan') # ce n'est pas un nan

In [5]:
type(a)==type(b)  # comparaison


True

In [6]:
np.isnan(Matrice) # val manquantes

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [7]:
np.isnan(Matrice).sum(axis=1) # axis=1 :par ligne on boucle sur éléments des colonnes 


array([0, 0, 1])

In [8]:
np.isnan(Matrice).sum() # au total

1

In [9]:

np.isnan(Matrice).sum(axis=0) # axis=0 :par col on boucle sur éléments des lignes

array([0, 1, 0])

In [10]:

del(b) # supprimer l'objet b

In [11]:
type(Matrice) # type de l'objet

numpy.ndarray

In [ ]:

dir(Matrice) # dir liste les attr / methodes d'un objet

In [13]:
Matrice.shape # shape est un attribut

(3, 3)

In [14]:
Matrice.ravel() # ravel est une méthode

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan,  9.])

In [15]:
# création d'une matrice, stockage par défaut en float64, ici int32
Matrice = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int)

In [16]:
# on applique la méthode mean() à l'objet numpy.ndarray moyenne des colonnes
Matrice.mean(axis=0)

array([4., 5., 6.])

In [17]:
# shape et ndim sont des attributs enregistrés
Matrice.shape ; Matrice.ndim

2

In [20]:
# python est un langage objet : sur la somme des colonnes, on applique une somme
Matrice.sum(axis=0).sum()

45

In [21]:
# équivalent à la dernière val de l'array envoyée par cumsum
Matrice.cumsum()[-1]
    # on travaille par ligne quand on fait cumsum donc -2 fait 45-9

45

In [23]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9],[10,np.nan,12]],dtype=float)

In [24]:
# Comprendre axis=0 , axis =1
# axis = 0 signifie qu'on analyse les colonnes (pour chaque col, on applique la fonction sur les lignes)
# axis=1 signifie qu'on analyse par lignes 

print(np.isnan(matrice).sum(axis=1)) # axis=1 :par ligne on boucle sur éléments des colonnes 
print(np.isnan(matrice).sum()) # au total
print(np.isnan(matrice).sum(axis=0)) # axis=0 :par col on boucle sur éléments des lignes

[0 0 0 1]
1
[0 1 0]


axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).


In [25]:
# moyenne avec numpy et pandas par colonne
print(matrice.mean(axis=0))

[5.5 nan 7.5]


In [ ]:
df = pd.DataFrame(matrice)
print(df.mean(axis=0))

In [ ]:
# sur certaines fonctions, le raisonnement est inversé : axis = 1 raisonne ici par colonnes
df.columns=["v1","v2","v3"]

In [ ]:
df.drop("v1", axis=1)