# LAMBDA FUNCTION
Elles s'utilisent à la volée dans une fonction map ; apply, applymap, filter qui s'applique la fonction définie dans le lambda à chaque élément d'un objet iterable

In [1]:
# on crée un tuple
numbers = (1, 2, 3, 4)

In [2]:
# utilise la lambda func pour à tout x renvoyer f(x)=x²
# map applique une fonction à un iterable, ici le tuple
result = list(map(lambda x: x*x, numbers))

In [3]:
# autre fonction
result= list(map(lambda x: x==1.00, numbers))
print(result)
result.count(False)

[True, False, False, False]


3

# Création de fonction

In [4]:
# création d'une fonction qui renvoie le carré de x
def fonc_carre(x):
    return x**2

In [5]:
fonc_carre(-10)

100

In [6]:
# Si l'utilisateur utilise mal la fonction, on a une erreur
fonc_carre('5')

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [7]:
# On va donc attraper cette erreur pour programmer un comportement face à cette erreur
def fonc_carre(x):
    try:
        return x**2
    except TypeError:
        print("x n'est pas un nombre!!!")  
    

In [8]:
fonc_carre('5')

x n'est pas un nombre!!!


In [9]:
fonc_carre(2)

4

In [10]:
# fonction en dur avec gestion des exceptions
from math import sqrt
def _sqrt(x):
    try:
        x>=0
        return sqrt(x)
    except:
        x<0
        print("calcul impossible")
    
    # test
    _sqrt(-5)
    _sqrt(+5)

In [11]:
result=list(map(_sqrt, numbers))  # Output [2, 4, 6, 8]
print(result)

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0]


# Exemple fonction standardisation

In [12]:
# créons un vecteur de données numérique en objet array
import numpy as np
Matrice = np.array(range(10))

In [13]:
# créons une fonction qui standardise un vecteur (type 1darray) : centrer et réduire (soustraire la moyenne et diviser par l'écart type)
# x doit etreu un np.array car on applique dessus np.mean ...
def standardisation(x): 
        x-=np.mean(x) # the -= means can be read as x = x- np.mean(x)
        x/=np.std(x)
        return x

In [16]:
# si on applique la fonction sur un array non float il y a un erreur
standardisation(Matrice)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [15]:
# appliquons la fonction standardisation, attention aux types des données
standardisation(Matrice.astype(float))

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [17]:
# Introduire une gestion d'exception dans la fonction => try except
def standardisation(x): 
    try:        
        x-=np.mean(x) # the -= means can be read as x = x- np.mean(x)
        x/=np.std(x)
        return x
    except TypeError:
        print("le type des données n'est pas float")

In [18]:
standardisation(Matrice)

le type des données n'est pas float


In [20]:
standardisation(Matrice.astype(float))

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [21]:
# si matrice2 n'est pas un array mais un tuple
# cela marche car np.mean fonctionne sur une liste de val numériques
matrice2=(1,2,3,4)
standardisation(matrice2)

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])